# Callback data
START, ARCHIVE, START_OVER, MANAGEMENT, EDIT, CREATE, GO_BACK = (
    'START',
    'ARCHIVE',
    'START_OVER',
    'MANAGEMENT',
    'EDIT',
    'CREATE',
    'GO_BACK',
)

# Stages
TOP_LEVEL, CREATE_EVENT, CREATE_DATE, CREATE_PROPERTY, CREATE_PHOTO = range(5)

(
    EDIT_NAME,
    EDIT_CITY,
    EDIT_DESC,
    EDIT_DATE_START,
    EDIT_DATE_END,
    EDIT_COUNTRY,
    EDIT_PHOTO,
    EDIT_PREVIEW,
    PUBLISH_EVENT
) = (
    'EDIT_NAME',
    'EDIT_CITY',
    'EDIT_DESC',
    'EDIT_DATE_START',
    'EDIT_DATE_END',
    'EDIT_COUNTRY',
    'EDIT_PHOTO',
    'EDIT_PREVIEW',
    'PUBLISH_EVENT'
)

FLAG_RU, FLAG_TR, FLAG_HR = (
    "\U0001F1F7\U0001F1FA",
    "\U0001F1F9\U0001F1F7",
    "\U0001F1ED\U0001F1F7",
)